MDScreen:
    name: "splash"
    MDFloatLayout:

        Image:
            source:"Images/Background.png"
            size_hint: 0.9, 0.9
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        Image:
            source:"Images/Logo.png"
            size_hint: 0.5, 0.5
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}

        Image:
            source: "Images/SLTC_Logo.png"
            size_hint: 0.6, 0.6
            pos_hint: {'center_x': 0.5, 'center_y': 0.1}
